<?php
    //From Information
    $inputMobileServiceProviderFrom = $_POST['inputMobileServiceProviderFrom'];
    $inputMobileNumberFrom = $_POST['inputMobileNumberFrom'];
    $inputEmailFrom = $_POST['inputEmailFrom'];
    $fromSenderInfoType = $_POST['fromSenderInfoType'];
    $inputFrom = "";
    //To Information
    $inputMobileServiceProviderTo = $_POST['inputMobileServiceProviderTo'];
    $inputMobileNumberTo = $_POST['inputMobileNumberTo'];
    $inputEmailTo = $_POST['inputEmailTo'];
    $toRecipientInfoType = $_POST['toRecipientInfoType'];
    $inputTo = "";
    //Correct - Mail Contents
    $inputSubject = $_POST['inputSubject'];
    $inputMessage = $_POST['inputMessage'];
    //Function To Change Email Based On Service Provider Selected
    function checkServiceProvider($inputServiceProvider) {
        $serviceProvider = "";
        if ($inputServiceProvider === "Verizon") {
            $serviceProvider = "@vtext.com";
        } elseif ($inputServiceProvider === "ATT") {
            $serviceProvider = "@txt.att.net";
        } elseif ($inputServiceProvider === "TMobile") {
            $serviceProvider = "@tmomail.net";
        } elseif ($inputServiceProvider === "Sprint") {
            $serviceProvider = "@messaging.sprintpcs.com";
        } else {
            echo "<script>alert('I\'m sorry but a Service Provider wasn\'t found, please try again!')</script>";
        }
        return $serviceProvider;
    }
    //Function To "Clean-Up" The Inputted Phone Number
    function cleanPhoneNumber($inputMobileNumber) {
        $searchArray = array(" ", "-", "(", ")", "+1");
        $inputMobileNumber = str_ireplace($searchArray, "", $inputMobileNumber);
        return $inputMobileNumber;
    }
    //If the user selected Sender Email
    if ($fromSenderInfoType == "email") {
        //Use Email
        $inputFrom = $inputEmailFrom;
    }
    //If the user selected Sender Phone Number
    elseif ($fromSenderInfoType == "mobileNumber") {
        //Use Email Generated by Phone Number and provided Service Provider
        $inputFrom = cleanPhoneNumber($inputMobileNumberFrom) . checkServiceProvider($inputMobileServiceProviderFrom);
    }
    //If the user selected Recipient Email
    if ($toRecipientInfoType == "email") {
        //Use Email
        $inputTo = $inputEmailTo;
    }
    //If the user selected Recipient Phone Number
    elseif ($toRecipientInfoType == "mobileNumber") {
        //Use Email Generated by Phone Number and provided Service Provider
        $inputTo = cleanPhoneNumber($inputMobileNumberTo) . checkServiceProvider($inputMobileServiceProviderTo);
    }
    //Wrap The Main Message Every 70 Characters
    $inputMessage = wordwrap($inputMessage, 70, "\r\n");
    //Set The From: and Reply-To: fields in the email
    $mailHeaders = "From: $inputFrom\r\nReply-To: $inputFrom";
    //Actually Send The Email/Text
    mail($inputTo, $inputSubject, $inputMessage, $mailHeaders);
    //Tell The User Their Message Has Been Sent And Load The Page
    echo "<script>alert('Your message has been sent, it will be received shortly...');</script>";
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Send A One-Time Text</title>
    <style>
        body {
            margin: 0;
        }
        iframe {
            width: 100%;
            height: 100%;
            border: none;
        }
    </style>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <!--Load The Previous Page (Endless-Loop)-->
    <iframe src="demo.html"></iframe>
</body>
</html>